Fix error in texture-demo-gcc
There was an undefined reference to texture
texture_star in texture-demo-gcc.
texture_star is not in repository so reference tp
it was removed to fix error.